name: contact_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^1.1.6
  http: ^1.2.1
  flutter_launcher_icons: "^0.13.1"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  fonts:
    - family: rsu
      fonts:
        - asset: fonts/RSU_BOLD.ttf
          weight: 700
        - asset: fonts/RSU_Regular.ttf
          weight: 500
        - asset: fonts/RSU_light.ttf
          weight: 400
